# Generated by Django 5.0.6 on 2024-06-12 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('internship_test', '0003_city_hotel_delete_mymodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hotel',
            old_name='city',
            new_name='city_code',
        ),
        migrations.RenameField(
            model_name='hotel',
            old_name='name',
            new_name='name',
        ),
    ]
