# Generated by Django 5.0.6 on 2024-06-12 08:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internship_test', '0004_rename_city_hotel_city_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='city_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hotels', to='internship_test.city'),
        ),
    ]
